config_version: 1

database:
  server_address: '127.0.0.1'
  server_port: '3306'
  db_name: 'g2plocaltest'
  db_user: 'root'
  db_password: ''

machines:
  default_drop_multiplier: 1.0
  max_drop_multiplier: 5.0

  commands_cooldown: 3 # in seconds
  repair_cooldown: 5 # in seconds
  stone_frequency: 40 # number in ticks (20 = 1 second)

  drop_exp_to_feet: true # drops exp orbs under player
  drop_items_to_feet: true # drops exp orbs under player

  allow_hopper_output: true # pass stone machine drops to hopper under it
  allow_hopper_input: true # allow upgrading stone machines with hopper input (Coal & Redstone Blocks)

primitive_drop:
  custom_name: 'Stone'
  miner_exp: 1 # Integer exp value for mining level
  weight: 63.9
  minimal_exp: 0
  maximal_exp: 0
  ignore_fortune: true
  multipliable: false
  default_tool:
    material: 'COBBLESTONE'
    magic_data: 0
    lore:
      - '&7Default Drop'
  silk_touch_tool:
    material: 'STONE'
    magic_data: 0
    lore:
      - '&7Drop Silktouch'

custom_drops:
  coal:
    miner_exp: 2
    weight: 11.6 # float value
    minimal_exp: 1
    maximal_exp: 5
    multipliable: true #If set to 'true' then accepts current drop multiplication set by server admin
    default_tool:
      material: 'COAL' # Bukkit Material
      magic_data: 0
      custom_name: '' # for default item name leave empty: '' or don't include in config section
      lore: # for no lore don't include this config section
        - '&7Default Drop'
      minimal_amount: 1
    silk_touch_tool:
      material: 'COAL_ORE'
      magic_data: 0
      custom_name: ''
      lore:
        - '&7Drop Silktouch'

  iron:
    miner_exp: 2
    weight: 5.1
    ignore_fortune: true
    multipliable: true
    default_tool:
      material: 'IRON_ORE'
      magic_data: 0
      custom_name: ''
      lore:
        - '&7Default drop only'

  gold:
    miner_exp: 1
    weight: 1.2
    ignore_fortune: true
    multipliable: true
    default_tool:
      material: 'GOLD_ORE'
      magic_data: 0
      custom_name: ''
      lore:
        - '&7Default drop only'

  diamond:
    #minimal_miner_lvl # minimal mining level needed to drop this item from stone
    #minimal_tool_lvl # minimal tool's material needed to drop this item from stone
    miner_exp: 4
    weight: 1.0 # float value
    minimal_exp: 1
    maximal_exp: 5
    multipliable: true #If set to 'true' then accepts current drop multiplication set by server admin
    default_tool:
      material: 'DIAMOND' # Bukkit Material
      magic_data: 0
      custom_name: '' # for default item name leave empty: '' or don't include in config section
      lore: # for no lore don't include this config section
        - '&7Default Drop'
      minimal_amount: 1
    silk_touch_tool:
      material: 'DIAMOND_ORE'
      magic_data: 0
      custom_name: ''
      lore:
        - '&7Drop Silktouch'

  redstone:
    miner_exp: 3
    weight: 5.5 # float value
    minimal_exp: 1
    maximal_exp: 5
    multipliable: true
    default_tool:
      material: 'REDSTONE' # Bukkit Material
      magic_data: 0
      custom_name: '' # for default item name leave empty: '' or don't include in config section
      lore: # for no lore don't include this config section
        - '&7Default Drop'
      minimal_amount: 4
      maximal_amount: 5
    silk_touch_tool:
      material: 'REDSTONE_ORE'
      magic_data: 0
      custom_name: ''
      lore:
        - '&7Drop Silktouch'

  lapis:
    miner_exp: 3
    weight: 0.1 # float value
    minimal_exp: 1
    maximal_exp: 5
    multipliable: true
    default_tool:
      material: 'LAPIS_LAZULI' # Bukkit Material enum name
      magic_data: 0
      custom_name: '' # for default item name leave empty: '' or don't include in config section
      lore: # for no lore don't include this config section
        - '&7Default Drop'
      minimal_amount: 4
      maximal_amount: 8
    silk_touch_tool:
      material: 'LAPIS_ORE'
      magic_data: 0
      custom_name: ''
      lore:
        - '&7Drop Silktouch'