config_version: 2

database:
  # available connectors: sqlite, mysql
  connector: 'sqlite'

  # settings for MySQL connector
  server_address: 'localhost'
  server_port: 3306
  db_name: 'stoneage'
  db_user: 'root'
  db_password: ''
  db_ssl: true

machines:
  destroy_tool: GOLDEN_PICKAXE
  
  default_drop_multiplier: 1.0
  max_drop_multiplier: 5.0 # admin exploit security

  max_miner_level: 99

  commands_cooldown: 3 # in seconds
  repair_cooldown: 5 # in seconds
  stone_frequency: 40 # number in ticks (20 = 1 second)

  drop_exp_to_feet: true # drops exp orbs under player
  drop_items_to_feet: true # drops exp orbs under player

  allow_hopper_output: true # pass stone machine drops to hopper under it
  allow_hopper_input: true # allow upgrading stone machines with hopper input (Coal)

# resource relations
resources:
  STONE:
    - coal
    - diamond
    - gold
    - iron
    - lapis
    - mending
    - redstone

  STONE_BRICKS:
    - coal
    - mending

# resources:
#   drops/primitives/*
#     - drops/*
